export const FETCH_ITEMS = "FETCH_ITEMS"
export const FETCH_CATEGORIES = "FETCH_CATEGORIES"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const EMPTY_CART = "EMPTY_CART"

